apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
data:
  init-db.sql: |
    CREATE SCHEMA IF NOT EXISTS user_schema;
    CREATE SCHEMA IF NOT EXISTS product_schema;
    CREATE SCHEMA IF NOT EXISTS order_schema;
    CREATE SCHEMA IF NOT EXISTS notification_schema;
