apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-deploy
  labels:
    app: notify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notify
  template:
    metadata:
      labels:
        app: notify
    spec:
      serviceAccountName: sallijang-notify-sa
      containers:
      - name: notify-container
        image: notify-image
        ports:
        - containerPort: 8003
        env:
        - name: DB_HOST
          value: "pickup-dev-rds-proxy.proxy-c1ckoyqwsimf.ap-northeast-2.rds.amazonaws.com"
        - name: DB_USER
          value: "adminuser"
        - name: DB_NAME
          value: "pickupdb"
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: user-service-secret
              key: secret-key
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service"
        - name: ORDER_SERVICE_URL
          value: "http://order-service"
        - name: REDIS_URL
          value: "rediss://pickup-dev-redis-001.pickup-dev-redis.n5yr9i.apn2.cache.amazonaws.com:6379"
        - name: SQS_QUEUE_URL
          value: "https://sqs.ap-northeast-2.amazonaws.com/594486941613/pickup-dev-reservation"
        - name: SNS_TOPIC_ARN
          value: "arn:aws:sns:ap-northeast-2:594486941613:pickup-dev-notification"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"