apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yaml
- deployment.yaml
- service.yaml

images:
- name: notify-image
  newName: 594486941613.dkr.ecr.ap-northeast-2.amazonaws.com/sallijang-backend-notify
  newTag: 21c34699d6dff8ebb2cbf9519cdfb62554b57444
