apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yaml
- deployment.yaml
- service.yaml

images:
- name: frontend-image
  newName: 594486941613.dkr.ecr.ap-northeast-2.amazonaws.com/sallijang-frontend
  newTag: c86d6c4feba218a13ba50a6c7ac3eafe60b0cc8c
