apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deploy
  labels:
    app: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      serviceAccountName: sallijang-product-sa
      containers:
      - name: product-container
        image: product-image
        ports:
        - containerPort: 8001
        env:
        - name: DB_HOST
          value: "pickup-dev-rds-proxy.proxy-c1ckoyqwsimf.ap-northeast-2.rds.amazonaws.com"
        - name: DB_USER
          value: "adminuser"
        - name: DB_NAME
          value: "pickupdb"
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: user-service-secret
              key: secret-key
        - name: REDIS_URL
          value: "rediss://pickup-dev-redis-001.pickup-dev-redis.n5yr9i.apn2.cache.amazonaws.com:6379"
        - name: IMAGE_BUCKET_NAME
          value: "pickup-dev-images"
        - name: CDN_URL
          value: "https://cdn.sallijang.shop"
        - name: STOCK_DEDUCT_QUEUE_URL
          value: "https://sqs.ap-northeast-2.amazonaws.com/594486941613/pickup-dev-stock-deduct"
        - name: STOCK_RESULT_QUEUE_URL
          value: "https://sqs.ap-northeast-2.amazonaws.com/594486941613/pickup-dev-stock-result"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"