apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yaml
- deployment.yaml
- service.yaml
- hpa.yaml

images:
- name: product-image
  newName: 594486941613.dkr.ecr.ap-northeast-2.amazonaws.com/sallijang-backend-product
  newTag: 4689a383f3b92dd1bba5ff364a34c506290b6aef
