apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yaml
- deployment.yaml
- service.yaml
- hpa.yaml

images:
- name: product-image
  newName: 594486941613.dkr.ecr.ap-northeast-2.amazonaws.com/sallijang-backend-product
  newTag: c703fe6848422cdf32dbefc5d07bcc8926f88e4e
