apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yaml
- deployment.yaml
- service.yaml
- hpa.yaml

images:
- name: product-image
  newName: 594486941613.dkr.ecr.ap-northeast-2.amazonaws.com/sallijang-backend-product
  newTag: 0dd68769fd77e57aec570a06d736f10f0b79c996
