apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deploy
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      serviceAccountName: sallijang-order-sa
      containers:
      - name: order-container
        image: order-image
        ports:
        - containerPort: 8002
        env:
        - name: DB_HOST
          value: "pickup-dev-rds-proxy.proxy-c1ckoyqwsimf.ap-northeast-2.rds.amazonaws.com"
        - name: DB_USER
          value: "adminuser"
        - name: DB_NAME
          value: "pickupdb"
        - name: AWS_REGION
          value: "ap-northeast-2"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"