apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deploy
  labels:
    app: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      serviceAccountName: sallijang-order-sa
      containers:
      - name: order-container
        image: order-image
        ports:
        - containerPort: 8002
        env:
        - name: DB_HOST
          value: "pickup-dev-rds-proxy.proxy-c1ckoyqwsimf.ap-northeast-2.rds.amazonaws.com"
        - name: DB_USER
          value: "adminuser"
        - name: DB_NAME
          value: "pickupdb"
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: user-service-secret
              key: secret-key
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service"
        - name: REDIS_URL
          value: "redis://pickup-dev-redis-001.pickup-dev-redis.n5yr9i.apn2.cache.amazonaws.com:6379"
        - name: SQS_QUEUE_URL
          value: "https://sqs.ap-northeast-2.amazonaws.com/594486941613/pickup-dev-reservation"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"