apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yaml
- deployment.yaml
- service.yaml

images:
- name: user-image
  newName: 594486941613.dkr.ecr.ap-northeast-2.amazonaws.com/sallijang-backend-user
  newTag: 26ded74d5a6d92d2b9fcd0e5474ecd379909bc8b
