apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/notify

patches:
- patch: |-
    - op: replace
      path: /metadata/annotations/eks.amazonaws.com~1role-arn
      value: "arn:aws:iam::594486941613:role/pickup-prod-notify-sa-role"
  target:
    kind: ServiceAccount
    name: sallijang-notify-sa

patchesStrategicMerge:
- patch-deployment.yaml
